### ISSUE TITLE
Make the first parameter of fieldDeletgate optional 

### ISSUE THREAD

**Issue by jimador** [TillaTheHun0/tilla#22]
When using `fieldDeletgate` for a computed field, you always pass `undefined` in as the first argument. The example from the docs is:

```js
let personTransformer = new Transformer({
 ...
  name: fd(undefined, always(buildWith(
    src => `${src.firstName} ${src.lastName}`
  ))),
  ...
}).byDefault(['age', 'height']).PASSTHROUGH()
```

It would be convenient if you could avoid having to pass `undefined` and just pass the function that computes the field value. Modified example from docs: 

```js
let personTransformer = new Transformer({
 ...
  name: fd(always(buildWith(
    src => `${src.firstName} ${src.lastName}`
  ))),
  ...
}).byDefault(['age', 'height']).PASSTHROUGH()
```

**Comment by TillaTheHun0** [comment]
Implemented in 9336019314bc992aa649cfa9c72c618719082b2e and released as part of [v2.1.0](https://github.com/TillaTheHun0/tilla/releases/tag/v2.1.0)
